FORMAT: 1A

# Agenda

Agenda is a simple API allowing consumers to schedule meeting online.

# Group User

Resource operations related to a user in the API.

## User-Key [/v1/key]

### Get user key [GET /v1/key{?username,password}]

Get a security key for operations.

+ Parameters
    - username : `alice` (string, required) - User Name
    - password : `iloveu` (required) - Password

+ Response 200 (application/json)

        {
            "key":"6384e2b2184bcbf58eccf10ca7a6563c"
        }
        
### Create a New User [POST]

+ Request (application/json)

        {
            "username":"bob",
            "password":"iloveu2",
            "email":"bob@gmail.com"
            "phone":"12345678901"
        }

+ Response 201 (application/json)

    + Body

            {
                "id":1,
                "key":"9f9d51bc70ef21ca5c14f307980a29d8",
                "username":"bob",
                "password":"iloveu2",
                "email":"bob@gmail.com",
                "phone":"12345678901"
            }

# Group Users

Resources related to users in the API.

## Users Collection [/v1/users{?key}]

+ Parameters
    - key : `6384e2b2184bcbf58eccf10ca7a6563c` (string, required)

### List all Users [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "key": "******",
                "username":"alice",
                "password":"******",
                "email":"alice@gmail.com",
                "phone":"10987654321"
            }, {
                "id":2,
                "key": "******",
                "username":"bob",
                "password":"******",
                "email":"bob@gmail.com",
                "phone":"12345678901"
            }
        ]

### Delete current user [DELETE]
    
+ Response 204

# Group Meetings

Resources related to users in the API.

## Meetings Collection [/v1/meetings{?key}]

+ Parameters
    - key : `6384e2b2184bcbf58eccf10ca7a6563c` (string, required)

### List all meetings [GET]

+ Response 200 (application/json)

        [
            {
                "id":1,
                "title":"AMeeting",
                "host":"alice",
                "members":["bob"],
                "starttime":"2017/12/25/13:00",
                "endtime":"2017/12/25/17:00"
            },{
                "id":2,
                "title":"BMeeting",
                "host":"bob",
                "members":["alice", "tracy"],
                "starttime":"2017/12/26/13:00",
                "endtime":"2017/12/26/17:05"
            }
        ]

### Create a meeting [POST]

+ Request (application/json)

        {
            "title":"Meeting4Bob",
            "members":["bob"],
            "starttime":"2017/12/25/23:00",
            "endtime":"2017/12/26/05:00"
        }

+ Response 201 (application/json)

    + Body

            {
                "id": 3,
                "title":"Meeting4Bob",
                "host":"alice",
                "members":["bob"],
                "starttime":"2017/12/25/23:00",
                "endtime":"2017/12/26/05:00"
            }

### Clear all meeting the user hosts [DELETE]

+ Response 204